### ISSUE TITLE
로그인 로그아웃 구현

### ISSUE THREAD

**Issue by 76cHel** [PetHaha/PetHaha#3]
## 목적
> 로그인 로그아웃 구현
## 작업 상세 내용
- [x] 로그인 기능 구현
- [x] 로그아웃 시, 로그아웃 되었습니다 alert 띄우기

## 참고사항
- 회원정보 수정은 이 브랜치에서 작성 되었습니다.

**Comment by jinnspace** [comment]
기능 구현이 끝났습니다.
